name: Deploy macktime API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: '20'

      - name: Install dependencies and Build
        run: |
          npm install
          npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/repos/macktime-server

            git pull origin main

            npm install
            npm run build

            pm2 restart macktime-server --update-env || pm2 start dist/index.js --name macktime-server